### ISSUE TITLE
current location slide does not load properly with `current location` activated

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#101]
Current location slide does not load properly with `current location` activated.
Steps to reproduce:
- activate location service of device
- activate `current location` in app
- let app go to background (e.g. switch to other app)
- return to app

Result:
- the height of the current location slide is not correctly established (probably taken from `<div *ngIf="currentLocationError && !loc.latitude" style="height: 350px;">` in `belaqi-user-location-slider.html`):

![screenshot_20190122-100535](https://user-images.githubusercontent.com/323719/51527222-5124a700-1e34-11e9-8288-aefe131958ea.png)

**Comment by janschulte** [comment]
Should be fixed with: 511593226b88ad01ac9130decaaceb9d934d0f86

**Comment by opeeters** [comment]
The case returning from background is not solved. Steps to reprduce:
- open app
- open app again (or open again after going to other app)

![screenshot_20190124-151929](https://user-images.githubusercontent.com/323719/51684391-3a28b500-1fec-11e9-907b-8f06800b5f61.png)

**Comment by opeeters** [comment]
This still remains a problem appearing much to often on both iOS and Android

**Comment by opeeters** [comment]
This is not only limited to the `current location` slide

**Comment by janschulte** [comment]
Add mechanism, which resizes the slide, when all child components are ready.
5fa0d9a854770c299888f7f8810efb828cdcfa57
