### ISSUE TITLE
overlay button hidden on recent iPhone models

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#141]
In the Xcode emulator for iPhone X or later, the overlay button is hidden. See:
![Simulator Screen Shot - iPhone Xʀ - 2019-03-28 at 14 42 31](https://user-images.githubusercontent.com/323719/55162321-dcd5ef00-5167-11e9-9a2e-f39deca78909.png)

All is well on iPhone 8 or older

**Comment by opeeters** [comment]
might be related to #144

**Comment by SpeckiJ** [comment]
IOS 10+ introduced a new concept where the border areas can also be used by the apps. This currently breaks our position calculation for the fixed header.

See also here: [https://stephenradford.me/removing-the-white-bars-in-safari-on-iphone-x/](https://stephenradford.me/removing-the-white-bars-in-safari-on-iphone-x/)

For now I have disabled the new feature, the App is now letterboxing and not using the additional space.

**Comment by opeeters** [comment]
still looks like this:

![Simulator Screen Shot - iPhone 8 - 2019-04-01 at 15 43 25](https://user-images.githubusercontent.com/323719/55332221-41a98600-5495-11e9-9842-f64d9db2d687.png)

Both in a simulator and on a iPhone 6 device..

On the simulated iPhone X, there is both a problem at the top and the bottom:

![Simulator Screen Shot - iPhone X - 2019-04-01 at 15 48 43](https://user-images.githubusercontent.com/323719/55332475-c4cadc00-5495-11e9-9183-c529bb6b084d.png)

**Comment by SpeckiJ** [comment]
I'm trying to reproduce this issue but have some difficulties with this. Below you see the screenshots with different iPhones running in the Xcode Simulator.

In our simulation with the iPhone 6 it seems to be working correctly. But as you have shown on your screenshots, the issue still persists.

One other strange thing: On the simulated iPhone X the notch at the top of the phone is missing in your simulation while it is included in our simulation. Is it possible that something goes wrong during the simulation?

We will check if there are some other ways to deal with this. 

Because I cannot reproduce this issue at the moment, it would be helpful if you could let me know if the changes to variables.scss solve your issue.

<img width="1238" alt="Screenshot 2019-04-01 at 07 47 48" src="https://user-images.githubusercontent.com/13851077/55337402-71d03500-5453-11e9-801b-811193376d60.png">

**Comment by opeeters** [comment]
The changes to `variables.scss` are not picked up. Which XCode version are you using? I'm on `10.2`.
Please also make sure that you commited all changes. When I do a project wide search for `env(safe-area-inset` I only find:
```
.button-edit {
                    right: calc(60px + env(safe-area-inset-right));
                }
```
in `src/app/components/modal-user-location-list/modal-user-location-list.component.scss`

I also tried adding my rules to `ionic.scss`

**Comment by SpeckiJ** [comment]
I am using XCode 10.2 as well, and I am synced with the main Repo.

At the moment it seems that the env(safe-area-inset-<*>)-variables are only set by the System if `viewport-fit=cover` is set. Currently it is disabled as of commit https://github.com/irceline/aq-mobile-be/commit/390886abd6aebdb3db02e943199b2541c0fd81a6. However, even after enabling it again, the safe area is still returned as 0 (at least in the Simulators). Currently we are looking for other ways to find out the correct safe-area-dimensions. 

I will update the Ticket once we have a solution/suggestion.

**Comment by SpeckiJ** [comment]
This should now be fixed as of 1a41c79b8daf4cbe3f8a97a936bc652079e99d20

@opeeters It works on our Simulators. Can you check on yours (or even on a real device) if this fix works?

**Comment by opeeters** [comment]
On an iPhone 6 device all is well.
On Xcode simulator for iPhone X types the footer is still an issue:

![Simulator Screen Shot - iPhone X - 2019-04-02 at 20 41 34](https://user-images.githubusercontent.com/323719/55432954-82d48f80-5594-11e9-8167-27dfb0eb5307.png)

**Comment by SpeckiJ** [comment]
Ok, I thought this was intended and we wanted the offset there instead of having the buttons right next to the virtual home button.

Will remove the offset tomorrow morning.

**Comment by opeeters** [comment]
With clean clone the issue on iPhone X also seems to be fixed. Looks great for the rest ;-)
I'll close the issue for the time being...
