### ISSUE TITLE
remember time aggregation when switching pollutant tabs in map view

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#156]
When entering the map page via the `short-term exposure` panel, depending on the pollutant, the user is in `hmean` or `24hmean` time aggregation. This time aggregation state should be remembered when switching pollutant tabs.

When a user switches to a forecast (`dmean` of `today`, `day+1`, `day+2`, `day+3`) or long-term exposure time aggregation (`anmean`) this should also become the remembered time aggregation.

Pollutants with both `hmean` and `24hmean` should be treated as follows:
- when coming from `short-term exposure` this means `belaqi`-mode (`belaqi`, `no2_hmean`, `o3_hmean`,  `pm10_24hmean`, `pm25_24hmean`,  `bc_hmean`)
- when switching to `pm10_hmean` or `pm25_hmean`, this mean `hmean`-mode (`belaqi`, `no2_hmean`, `o3_hmean`,  `pm10_hmean`, `pm25_hmean`,  `bc_hmean`)

**Comment by SpeckiJ** [comment]
The basic functionality is implemented with https://github.com/irceline/aq-mobile-be/commit/ccbc1aa68425b82c68a8e322f3032bf9082466c2

The app now remembers the aggregation, and tries to match it when switching phenomena. It currently only remembers the last aggregation (so if you choose BC - afterwards you will be coerced into hmean/amean for all other phenomena).

If the aggregation is not available for the new phenomena (e.g. the case for 24hmean and basically all aggregations for BC), it falls back to the closest aggregation.

Currently no different modes are implemented as suggested above (tbd). Will update the issue once the different modes are implemented.

**Comment by SpeckiJ** [comment]
I have implemented different modes as of https://github.com/irceline/aq-mobile-be/commit/314e50ba7a4bd4e3bceb9b709284e1de0c52ac0e.

By default the `hmean-mode` is chosen. The mode is switched by adjusting the slider in either PM10 oder PM25. When adjusting the slider (in PM10 or PM25) the following happens:

- If the slider is on `24hmean`, the slider sets itself into `belaqi-mode`, and automatically switches from hourly to 24h means (if available) upon changing phenomena.
- If the slider is on `hmean`, the slider sets itself into `hmean-mode`, it then uses hmean as the aggregation upon changing phenomena.
- If the slider is in any other position, upon phenomena change it tries to match the aggregation and coerces to the closes possible aggregation if there is no matching aggregation. The coerced aggregation (e.g. hmean when switching to BC) is then the basis for further switches between phenomena.

As I am unsure whether I correctly understood the original intent, could you please review this change @opeeters?

**Comment by opeeters** [comment]
@SpeckiJ 
Looks very good, thanks!

One bizarre bug still. All is well with one user location configured. With two or more user locations (e.g. Brussels and Arlon), the map view misbehaves. 

E.g. when you go to the map page via any of the entry points (panels and navigation) you get this (after relaunching the app):

![Screenshot_20190423-152257](https://user-images.githubusercontent.com/323719/56584528-318c4e80-65dc-11e9-88fa-1bff7df45419.png)

And when switching to the BC tab, under some circumstances, e.g. go to no2_hmean first, than switch to bc, you get a bc forecast time aggregation. BC has no forecast.

Clearing the app cache does not help. Removing the second user location solves the issue..

**Comment by SpeckiJ** [comment]
The wrong warp to BC_Forecast is fixed with https://github.com/irceline/aq-mobile-be/commit/9794aeaa067a5e3abdeb3faff0aaef0ce1fbe6a4

The Screenshot above should only be shown for a very short time while the map initializes. I will check whether I can reproduce this issue (and then fix it) tomorrow.

**Comment by SpeckiJ** [comment]
Unfortunately I cannot reproduce the behaviour described above. The Maps always load after 1-2seconds on my device.

@opeeters Can you describe the steps you take to get this behaviour? E.g. Enter Location -> Exit app -> Reopen App -> Open Map page etc...

**Comment by opeeters** [comment]
seems to be OK now. I cannot reproduce this either.. closing issue for the time being.
