### ISSUE TITLE
automatich refresh after introduction

### ISSUE THREAD

**Issue by opeeters** [irceline/aq-mobile-be#95]
At the end of the introduction wizard it is always necessary to manually refresh (pull slide down) before the data from the configured locations is actually fetched. This is especially annoying for new users..

**Comment by janschulte** [comment]
fixed with: 4d70a43b62474a7f0b0a492bf83ab8f6b0eb390d

**Comment by opeeters** [comment]
still experienced problems on iOS in the emulator, but I still need to investigate whether this is also the case on a device.. Should anyone with an iOS be able to reproduce, please let me know.

keeping the issue open for the time being..
